### ISSUE TITLE
localızatıon

### ISSUE THREAD

**Issue by VB10** [StatelessW/bankingappUI#1]
https://github.com/StatelessW/bankingappUI/blob/c27a749ecb57a9514b2eb870690a70b82ee42818/lib/utility/project_strings.dart#L2

bu strınglerı tek tek gırmekle ugrasmak yerıne en json fıle ypaıp easy localızatıon kullanarak yapabilrisin kanalda bol bol var

**Comment by StatelessW** [comment]
EasyLocalization paketi ile json üzerinden okuttum. Kullanması çok keyifliymiş :) Teşekkür ederim.

**Comment by StatelessW** [comment]
EasyLocalization paketi ile json üzerinden okuttum. Kullanması çok keyifliymiş :) Teşekkür ederim.
